# Generated by Django 5.0.6 on 2024-07-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('km', models.CharField(max_length=20)),
                ('tiempo_estimado', models.CharField(max_length=50)),
                ('punto_inicio', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('ganancias', models.FloatField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('created', models.DateField(auto_now_add=True, verbose_name='fecha creación')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-created'],
            },
        ),
    ]
