# Generated by Django 5.0.6 on 2024-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='ganancias',
            field=models.FloatField(null=True),
        ),
    ]
