# Generated by Django 5.0.6 on 2024-08-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tours_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['id'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
