# Generated by Django 5.0.6 on 2024-08-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='lugares_disponibles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='punto_final',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
