# Generated by Django 5.0.6 on 2024-08-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_pagado',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
