# Generated by Django 5.0.6 on 2024-08-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_reserva_precio_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Cancelada')], default='1', max_length=10),
        ),
    ]
