# Generated by Django 5.0.6 on 2024-08-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='mapa',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
